Vagrant.configure('2') do |config|
  config.vm.define :"tst" do |tst|
    tst.vm.box = "ubuntu1404-desktop"
    tst.vm.hostname = "tst"
    tst.vm.provision :serverspec do |spec|
      spec.pattern = '../test/*_virtualbox.rb'
    end
    tst.vm.provider "vmware_fusion" do |v|
      v.gui = true
    end
    tst.vm.provider "virtualbox" do |v|
      v.gui = true
    end
  end
end

